---
- import_tasks: include-vars.yml

- import_tasks: install.yml
- import_tasks: config.yml

- include_tasks: manage_user.yml
  with_items: "{{ openldap_users }}"

- include_tasks: manage_group.yml
  with_items: "{{ openldap_groups }}"
