---

- name: Assign variables
  set_fact:
    openldap_userPassword: "{{ command_output.stdout }}"
    openldap_default_user:
      description: "{{ item.cn }}"

- name: merging variables
  set_fact: 
    openldap_groupsetting: "{{ openldap_default_user | combine(item) }}"

- name: Modify ldap group
  ldap_entry:
    dn: cn={{ item.cn }},{{ openldap_group_ou }}
    bind_dn: cn=Admin,{{ openldap_domain }}
    bind_pw: "{{ openldap_rootpw }}"
    objectClass:
      - top
      # - posixGroup
      - groupOfUniqueNames 
    attributes: "{{ openldap_groupsetting }}"
    state: "{{ item.state | default('present') }}"


